### ISSUE TITLE
Change tempo while playing

### ISSUE THREAD

**Issue by mdahlgrengadd** [wothke/libxmp-4.4.1#6]
Hi! Odd question...

I wonder if it is possible to adjust tempo (bpm) of playing module from javascript? I want to have background beats/scores when I practise music and be able to adjust tempo as i get better... 

Thanks,
Martin.

**Comment by wothke** [comment]
Hi 
Just tweek the desired output sample rate of the player. See http://www.wothke.ch/websid/ (right-hand slider in collapsed "What's this?" dialog).

Cheers,
Jürgen

**Comment by mdahlgrengadd** [comment]
oh, I apologise for not being clear. Your suggestion will also change pitch, if i'm not mistaken. I'm wondering if its possible to alter the modules tempo as defined in song info by composer. I understand it will be possible during loading, but im not sure how this could be changed during playback.

**Comment by wothke** [comment]
I don't know if such a functionality is available within the "original" libxmp and my web-version currently does not expose a respective feature to the "JavaScript world". (If a respectice "during loading" feature is already available in libxmp then it should be possible to export it for use in JavaScript. You got any pointer to the respective libxmp function you are interested in?)

**Comment by mdahlgrengadd** [comment]
Ok. I didn't find such functionality, but a workaround might be using the the function below to insert Fxx effect in FastTracker2 modules or Txx in s3m. 

void xmp_inject_event(xmp_context c, int channel, struct xmp_event *event)

**Comment by wothke** [comment]
no idea - I am not familiar with the details of those trackers.. if you want to try it, then you could patch my adapter.c with whatever additional functionality you want to expose to the "JavaScript world".. (see xmp_adapter.js for examples how the "exported" functions are  invoked via "ccall" - you'd have to use "backend_XMP.Module.ccall")

**Comment by mdahlgrengadd** [comment]
Ok, thanks for your help! Will look into this in the next few days.

**Comment by wothke** [comment]
I do not know if/how this might affect "pitch" but it might be worth trying: In "libxmp_load_prologue" there is a "m->time_factor" being set and from what I see that factor is used during playback.

I'd suggest you first set that value to something else (hard-coded) - just to check if that has the desired effect. If so, you (later) create some accessor function in adapter.c that lets you tweak that value, i.e. "module_data.time_factor" dynamically from the JavaScript side (make sure to design a function API that relies *exclusively* on built-in C-types, i.e. all the xmp-lib specific types must be handled within that function - since you cannot directly use them from the JavaScipt side..).

**Comment by mdahlgrengadd** [comment]
Indeed, it works! Thanks!

**Comment by wothke** [comment]
glad I could help :-)
